<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="Dear Reader, my name is Joseph Perrin, I am 22 years-old french student. I recently started my Master in Analytics and Management at London Business School.">
	<meta name="author" content="Joseph Perrin">
	<meta name="generator" content="Hugo 0.74.3" />
	<title>Tour de France &middot; Portfolio website for Joseph Perrin</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="/" class="logo"><strong></strong> <span>Joseph Perrin</span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="/">Home</a></li>
            

        </ul>
        <ul class="actions vertical">
            
                <li><a href="/pages" class="button special fit">My Work</a></li>
            
            
                <li><a href="/pages/aboutme" class="button fit">About me</a></li>
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>Tour de France</h1>
                            </header>
                            
                            


<p><br />
<br />
</p>
<p><img src="https://todaycycling.com/wp-content/uploads/2020/09/tadej-pogacar-%C3%A9tape-20-tour-de-france.jpg" style="width:50.0%" /><br />
<em>Tadej Pogacar, on his way to winning the 2020 Tour de France</em><br />
</p>
<div id="background-information" class="section level2">
<h2>Background Information</h2>
<p>As the Tour de France 2020 is currently underway, the peloton will have to ride over 3500km in a bit less than 3 weeks. While the outcome of this year’s Tour, the first one to happen in September, is quite certain, this race is usually the theatre of much suspense and drama. Every year since 1903, the Tour de France is a cycling race taking place in the summer which slowly became inherent to the french culture.</p>
<p>Today, any citizen will closely follow the route of the Tour and hope for it to pass by its village and get the chance to see the ‘real’ Maillot Jaune (leader of general classification).
But while this race is globally known for its difficulty, let us get a closer look to its history.</p>
<pre><code>## Rows: 104
## Columns: 12
## $ Year     &lt;dbl&gt; 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, …
## $ Stages   &lt;dbl&gt; 6, 6, 11, 13, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15…
## $ Started  &lt;dbl&gt; 60, 88, 60, 82, 93, 112, 150, 110, 84, 131, 140, 145, 69, 11…
## $ Ended    &lt;dbl&gt; 21, 27, 24, 14, 33, 36, 55, 41, 28, 41, 25, 54, 11, 22, 38, …
## $ Distance &lt;dbl&gt; 2428, 2428, 2994, 4637, 4488, 4488, 4497, 4734, 5343, 5289, …
## $ Hour     &lt;dbl&gt; 94, 96, 110, 189, 158, 156, 157, 162, 195, 190, 197, 200, 23…
## $ Minutes  &lt;dbl&gt; 33, 5, 26, 34, 45, 53, 1, 41, 37, 30, 54, 28, 7, 36, 50, 8, …
## $ Seconds  &lt;dbl&gt; 0, 56, 58, 0, 5, 29, 22, 30, 0, 28, 0, 48, 15, 13, 26, 6, 30…
## $ Pace     &lt;dbl&gt; 25.7, 25.3, 27.1, 24.5, 28.5, 28.7, 28.7, 29.1, 27.3, 27.8, …
## $ Winner   &lt;chr&gt; &quot;M. Garin&quot;, &quot;H. Cornet&quot;, &quot;L. Trousselier&quot;, &quot;R. Pottier&quot;, &quot;L.…
## $ Country  &lt;chr&gt; &quot;Fra&quot;, &quot;Fra&quot;, &quot;Fra&quot;, &quot;Fra&quot;, &quot;Fra&quot;, &quot;Fra&quot;, &quot;Lux&quot;, &quot;Fra&quot;, &quot;Fra…
## $ Age      &lt;dbl&gt; 32, 20, 24, 27, 24, 25, 22, 21, 27, 24, 23, 24, 33, 30, 33, …</code></pre>
</div>
<div id="tour-de-france-overview" class="section level2">
<h2>Tour de France Overview</h2>
<div id="the-tour-de-france-travels-less-distance-but-the-pace-is-dramatically-increasing" class="section level4">
<h4>The Tour de France travels less distance, but the pace is dramatically increasing</h4>
<p><img src="/blogs/tourdefrance/tourdefrance_files/figure-html/ataglance%20pace%20and%20distance-1.png" width="648" style="display: block; margin: auto;" /></p>
<p><img src="/blogs/tourdefrance/tourdefrance_files/figure-html/number%20of%20stages-1.png" width="480" style="display: block; margin: auto;" /></p>
<pre><code>## List of 3
##  $ axis.title.x : list()
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_blank&quot; &quot;element&quot;
##  $ plot.title   :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr &quot;bold&quot;
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0.5
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi FALSE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.subtitle:List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : num 4
##   ..$ hjust        : num 0.5
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi FALSE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;theme&quot; &quot;gg&quot;
##  - attr(*, &quot;complete&quot;)= logi FALSE
##  - attr(*, &quot;validate&quot;)= logi TRUE</code></pre>
<p>The first Tour de France was very short and consisted of only 8 stages. Rapidly, the number of stages increased and so did the distance of each Tour. Indeed the first Tours were almost 5000 km long on average, with the longest ever Tour taking place in 1926 (5745km!). In recent years the Tour de France was shorter (~3500km), with the shortest ever distance in the modern era appearing in 2002 with a total distance of 3278km (see table below).
Concerning the speed of the riders, the professionalization of the sport and the technological advances had the effect of dramatically increasing the speed of the peloton. The slowest Tour de France was run at an average speed of 24km/h while Lance Armstrong won one of his Tours at an average speed of over 41km/h. More recently, the Tour de France average pace stabilised, for evident physical reason (no man could cycle 3 weeks at average 80 km/h !), but also because the UCI (Union Cycliste Internationale) has implemented a growing number of standards and regulation to control the performance of riders.</p>
<pre><code>##   Year Pace       Winner
## 1 2005 41.7 L. Armstrong
## 2 2017 41.0    C. Froome
## 3 2003 40.9 L. Armstrong</code></pre>
<pre><code>##   Year Pace    Winner
## 1 1919 24.1 F. Lambot
## 2 1920 24.1   P. Thys
## 3 1922 24.2 F. Lambot</code></pre>
<pre><code>##   Year Distance
## 1 1926     5745
## 2 1919     5560
## 3 1920     5503</code></pre>
<pre><code>##   Year Distance
## 1 1903     2428
## 2 1904     2428
## 3 1905     2994</code></pre>
<pre><code>##   Year Distance
## 1 2002     3278
## 2 1989     3285
## 3 1988     3286</code></pre>
<p><strong>Records </strong><br />
Fastest Pace: <em>Lance Armstron (41.7 km/h)</em><br />
Slowest Pace: <em>Firmin Lambot (24.7 km/h)</em><br />
Shortest Tour: <em>1903, 1904 (2428 km)</em><br />
Shortest Modern Tour: <em>2002 (3278 km)</em><br />
Longest Tour: <em>1926 (5745 km)</em><br />
<br />
#### The number of riders and finishers of the Tour de France increased over time<br />
<img src="/blogs/tourdefrance/tourdefrance_files/figure-html/tour%20de%20france%20completion-1.png" width="672" style="display: block; margin: auto;" /></p>
<pre><code>## List of 5
##  $ axis.title.x : list()
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_blank&quot; &quot;element&quot;
##  $ axis.title.y :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr &quot;navy&quot;
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi FALSE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ axis.text.y  :List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : chr &quot;navy&quot;
##   ..$ size         : NULL
##   ..$ hjust        : NULL
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi FALSE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.title   :List of 11
##   ..$ family       : NULL
##   ..$ face         : chr &quot;bold&quot;
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0.5
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi FALSE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  $ plot.subtitle:List of 11
##   ..$ family       : NULL
##   ..$ face         : NULL
##   ..$ colour       : NULL
##   ..$ size         : NULL
##   ..$ hjust        : num 0.5
##   ..$ vjust        : NULL
##   ..$ angle        : NULL
##   ..$ lineheight   : NULL
##   ..$ margin       : NULL
##   ..$ debug        : NULL
##   ..$ inherit.blank: logi FALSE
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;element_text&quot; &quot;element&quot;
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;theme&quot; &quot;gg&quot;
##  - attr(*, &quot;complete&quot;)= logi FALSE
##  - attr(*, &quot;validate&quot;)= logi TRUE</code></pre>
<p><br />
The first years of the Tour de France were the theatre of an incredible spectacle between riders who would cycle night and day to join two cities. The lack of preparation and equipment led to many retirements and abandons. At the time, there were quite many disqualification as many occurrences of cheating, such as taking the train or a car to shorten the distance, were reported. However, drinking wine to boost your performance was not illegal!<br />
In the more recent era of cycling, the falls and crashes are the most common reason for abandons. Another reason explaining disqualifications are the maximum delay rules, which entails that participants must finish the stage under a certain time, a rule which can be difficult for some riders in the mountain stages.<br />
Note that the 1998 Tour de France saw the abandon of many cycling teams participating to the Tour due to the “Festina Scandal”, one of the first doping scandals of the sport.<br />
#### France is the counts the most wins</p>
<p><img src="/blogs/tourdefrance/tourdefrance_files/figure-html/tour%20de%20france%20winner%20country-1.png" width="648" style="display: block; margin: auto;" />
Let us now analyse the victories of the Tour de France, the most prestigious cycling race in the world.
With regards to nationality, France counts the most champions with 36 victories. Note however that the last French winner of the tour de France Bernard Hinault was in 1985… Belgium comes second with 18 victories while the Spain is third (12 victories).</p>
<p><strong>Records</strong><br />
7 Wins: <del><em>Lance Armstrong (USA)</em></del><br />
5 Wins: <em>Jacques Anquetil (FRA), Eddy Merckx (BEL), Bernard Hinault (GBR), Miguel Indurain (ESP)</em><br />
4 Wins: <em>Christopher Froome (GBR)</em><br />
3 Wins: <em>Philippe Thys (BEL), Louison Bobet (FRA), Greg LeMond (USA)</em><br />
2 Wins: <em>Lucien Petit-Breton (FRA), Firmin Lambot (BEL), Ottavio Bottecchia (ITA), Nicolas Frantz (LUX), André Leducq (FRA), Antonin Magne (FRA), Sylvère Maes (BEL), Gino Bartali (ITA), Fausto Coppi (ITA), Bernard Thévenet (FRA), Laurent Fignon (FRA), Alberto Contador (ESP)</em></p>
<pre><code>## # A tibble: 21 x 2
##    Winner       Count
##    &lt;chr&gt;        &lt;int&gt;
##  1 L. Armstrong     7
##  2 B. Hinault       5
##  3 E. Merckx        5
##  4 J. Anquetil      5
##  5 M. Indurain      5
##  6 C. Froome        4
##  7 G. LeMond        3
##  8 L. Bobet         3
##  9 P. Thys          3
## 10 A. Contador      2
## # … with 11 more rows</code></pre>
<p>With regards to individual winners of the Tour de France, the rider with the most victories is Lance Armstrong, which was however convicted of doping a few years and saw all his wins cancelled. 4 riders have won the Tour 5 times, and Christopher Froome who won it 4 times already will try to join them in the classification in the Tour 2021. In total, 21 riders won the Tour at least 2 times.</p>
</div>
<div id="tour-de-france-by-stages" class="section level3">
<h3>Tour de France By Stages</h3>
<p>The overall Tour de France is won by the cyclist that has the fastest culmulative time. However, there the fastest rider of each stage is still wildly celebrated and their wins contribute to the points classification as well as the team classification. Here, we take a closer look at the Tour de France Stage Winners.</p>
<div id="stage-wins-ranking-differ-from-tour-wins-ranking" class="section level4">
<h4>Stage Wins Ranking Differ from Tour Wins Ranking</h4>
<p><img src="/blogs/tourdefrance/tourdefrance_files/figure-html/stagedetails2%20stage%20win%20country%20distribution-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Once again, France has is the most decorated country in terms of stage wins with Belgium in second place. While Spain came in third in terms of Tour wins, it was fifth in terms of Stage wins. The Netherlands, which had won 2 Tours total, had won 157 Stages. On the other hand, if we still count the 7 Tour titles by Lance Armstrong, the USA had won 10 Tours while only winning 38 Stages. Winning more stages certainly makes it more likely to win the Tour, it seems that there is some wiggle room in the absolute rankings.</p>
<p>We also note that an unusually large portion of Spain’s victories come from Mountain Stages. Perhaps there’s something about Spanish racers make them particularly formidable opponents on climbs?</p>
<p><strong>Records</strong><br />
France: <em>36 Tour Wins, 691 Stage Wins</em><br />
Belgium: <em>18 Tour Wins, 460 Stage Wins</em><br />
Spain: <em>12 Tour Wins, 125 Stage Wins</em><br />
Italy: <em>10 Tour Wins, 262 Stage Wins</em><br />
USA: <em><del>10</del> 3 Tour Wins, 38 Stage Wins</em><br />
Great Britain: <em>5 Tour Wins, 67 Stage Wins</em><br />
Luxembourg: <em>2 Tour Wins, 70 Stage Wins</em><br />
Netherlands: <em>2 Tour Wins, 157 Stage Wins</em><br />
Switzerland: <em>2 Tour Wins, 57 Stage Wins</em></p>
</div>
<div id="cyclists-are-responsible-for-over-half-of-all-stage-victories" class="section level4">
<h4>~130 Cyclists are Responsible for Over Half of All Stage Victories</h4>
<p><img src="/blogs/tourdefrance/tourdefrance_files/figure-html/individual%20stage%20victories-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>When we plot the cumulative sum of the stage wins, we can see that around 130 cyclists can account for more than 50% of all the stages won during the Tour de France. Furthermore, we see that riders who have won a single stage only account for less than 25% of all stages.</p>
<p>Now, let’s hone in on the most decorated riders.</p>
<p><img src="/blogs/tourdefrance/tourdefrance_files/figure-html/stagedetails%20top%20stage%20riders-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Eddy Merckx is the most decorated rider with a whopping total of 34 stage wins. Furthermore, we notice that the majority of riders specialize in only two, if not one, of the three different stage categories. However, Eddy managed to win stages of all types. Other well-rounded cyclests include Bernard Hinault, André Leducq, <del>Lance Armstrong</del>, Nicolas Frantz, Jacques Anquetil, and Freddy Maertens. With the exception of Maertens, the remaining other all-rounder cyclists have all won the Tour de France during their career. Perhaps that is an indication that in order to win the Tour, one has to be outstanding across a variety of terrains.</p>
<p><strong>Records</strong><br />
Most Flat Stage Wins: <em>Mark Cavendish</em><br />
Most Mountain Stage Wins: <em>Eddy Merckx</em><br />
Most Time Trial Stage Wins: <em>Bernard Hinault</em></p>
</div>
<div id="stage-distances-have-also-shortened-over-the-years" class="section level4">
<h4>Stage Distances Have Also Shortened Over the Years</h4>
<p><img src="/blogs/tourdefrance/tourdefrance_files/figure-html/stagedetails%20stage%20distribution-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>We already knew that over the years, the total distance covered in the Tour de France has decreased. But what about on the individual stage level? Have stage distances decreased as well? It turns out, yes, they have. Every single stage type has decreased in length since the beginning of the Tour de France.</p>
<p>From the density plot on the right, we can see that generally, Time Trial Stages are the shortest, while Flat and Mountain Stages are comparable in length. We see that there is a small bump representing very long Mountain Stages that appears like an outlier. Upon closer inspection, we realize that long Mountain Stages are a relic of the past, occuring nearly exclusively before ~1930. During this time period, Time Trials were also much longer than modern day Trials.</p>
<p><img src="/blogs/tourdefrance/tourdefrance_files/figure-html/stage%20details%20stage%20histogram-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>We can also look at the distribution of stage types across the years. We see that when the Tour first began, there were very few stages, each being incredibly long. We also notice that Time Trial Stages were not actually introduced until 1927, when they became the most common stage. This persisted for one more year before they once again became the rarest stage. In recent years, the Tour de France has consisted of 21 stages. The average stage length (denoted by the black line) as well as minimum and maximum stage length (denoted by the grey ribbon) has been consistent as well.</p>
<p>Interestingly, the longest modern stage is shorter than even the shortest stage during the pre-WWI Tour de France. The Tour has changed dramatically over the years!</p>
</div>
</div>
<div id="conclusion-and-next-steps" class="section level3">
<h3>Conclusion and Next Steps</h3>
<p>It’s so interesting to see historial events emerge as outliers from this whirlwind tour of the history of the Tour de France. From identifying winners to looking at distance and stage trends, we can see that the Tour de France today is a very different race from the one that was started in 1903.</p>
<p>In the future, I would love to look in more detail about each individual cyclist’s performance and look for trends through the years. From what I understand, this data can be scraped from the <a href="https://www.letour.fr/en/history">Official Tour de France website</a>. This has been done by Thomas Camminady as stated on his <a href="https://www.camminady.org/every-cyclist-of-the-tour-de-france-in-a-single-csv-file/">website</a>. When I get a chance, I would love to do some exploratory data analysis on this dataset.</p>
</div>
<div id="final-note" class="section level3">
<h3>Final Note</h3>
<p>I was inspired to work on a Tour de France dataset thanks to the documentary “<strong>Eat, Race, Win</strong>”. As someone very new to the sport of cycling, the Tour de France, I am sure there are mistakes in my interpretations. Any advice, suggestions, or corrections are welcomed!</p>
<p>It seems that I am having trouble with Kaggle’s RMarkdown in getting ggExtra to update to v0.8, as well as trouble with geocode in getting a map to visualized. In this case, I simply enclosed an image of what the visualization should have looked like. To recreate these visualizations, the script should work (just not on Kaggle). Alternatively, for all the information regarding this analysis, please visit <a href="https://github.com/jamminliu/Tour-de-France-Exploration">my github</a></p>
<p><strong>Sources:</strong><br />
<a href="https://en.wikipedia.org/wiki/Tour_de_France">Wikipedia</a><br />
<a href="https://www.letour.fr/en/history">Le Tour de France Official Website</a><br />
<a href="https://www.kaggle.com/ralle360/historic-tour-de-france-dataset">Stage Details Dataset</a> by RasmusFiskerBang on <a href="www.kaggle.com">Kaggle</a></p>
</div>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery.scrolly.min.js"></script>
    <script src="/js/jquery.scrollex.min.js"></script>
    <script src="/js/skel.min.js"></script>
    <script src="/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="/js/main.js"></script>

    

    

    </body>
</html>
